apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - name: app-container
    image: rusita/app:v1
    ports:
    - containerPort: 80
      protocol: TCP

  - name: sidecar-container
    image: rusita/sidecar:curl
    command: ["tail"]
    args: ["-f", "/dev/null"]

