apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr-2
    image: rusita/cpu-stress
    resources:
      requests:
        cpu: "10000m"
      limits:
        cpu: "10000m"
    args:
    - -cpus
    - "2"

