apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: test-ns
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - image: rusita/app:v1
    name: app-container
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"
