apiVersion: v1
kind: Service
metadata:
  name: clusterip-hostname-service
spec:
  type: ClusterIP
  clusterIP: 10.96.0.100
  selector:
    app: hostname-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

