apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx-label
spec:
  replicas: 3
  selector:
    matchExpressions:
     - {key: app,operator: Exists}
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80

